package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketPriorityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketPriorityAllPropertiesEquals(TicketPriority expected, TicketPriority actual) {
        assertTicketPriorityAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketPriorityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketPriorityAllUpdatablePropertiesEquals(TicketPriority expected, TicketPriority actual) {
        assertTicketPriorityUpdatableFieldsEquals(expected, actual);
        assertTicketPriorityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketPriorityAutoGeneratedPropertiesEquals(TicketPriority expected, TicketPriority actual) {
        assertThat(actual)
            .as("Verify TicketPriority auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketPriorityUpdatableFieldsEquals(TicketPriority expected, TicketPriority actual) {
        assertThat(actual)
            .as("Verify TicketPriority relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketPriorityUpdatableRelationshipsEquals(TicketPriority expected, TicketPriority actual) {
        // empty method
    }
}
