package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCategoryAllPropertiesEquals(TicketCategory expected, TicketCategory actual) {
        assertTicketCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCategoryAllUpdatablePropertiesEquals(TicketCategory expected, TicketCategory actual) {
        assertTicketCategoryUpdatableFieldsEquals(expected, actual);
        assertTicketCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCategoryAutoGeneratedPropertiesEquals(TicketCategory expected, TicketCategory actual) {
        assertThat(actual)
            .as("Verify TicketCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCategoryUpdatableFieldsEquals(TicketCategory expected, TicketCategory actual) {
        assertThat(actual)
            .as("Verify TicketCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketCategoryUpdatableRelationshipsEquals(TicketCategory expected, TicketCategory actual) {
        // empty method
    }
}
